### ISSUE TITLE
Ability to add/remove hosts from existing hostgroups

### ISSUE THREAD

**Issue by rgroten** [Nosmoht/ansible-module-ipa#1]
A module that provides the ability to add or remove and existing host from a hostgroup(s).

**Comment by Nosmoht** [comment]
Fixed with: https://github.com/Nosmoht/ansible-module-ipa/commit/6080ad0339452d99dbf11f904c0c68127cbeb344

**Comment by Nosmoht** [comment]
pretty cool. i've added all my databases with this:

``` yaml
- ipa_hostgroup:
    name: oracle-server
    host: '{{ groups["oracle-server"] }}'
```

Thanks for issue @rgroten
