### ISSUE TITLE
ipa_group should allow for group names with spaces

### ISSUE THREAD

**Issue by slmingol** [Nosmoht/ansible-module-ipa#17]
I'm using the following task in a playbook

```
- set_fact:
    trust_admins: "trust admins"

- name: Create group {{ trust_admins }}
  ipa_group:
    name: "{{ trust_admins }}"
    description: "Trusts administrators group"
    nonposix: true
    user: "[ 'admin' ] + {{ ad_admins | map(attribute='qlid') | list }}"
    ipa_host: idm1.ipa.td.teradata.com
    ipa_user: admin
    ipa_pass: "{{ ipa_principal_password }}"
```

When I run this I get the following error
```
ASK [ipa_add_users : Create group trust admins] ***********************************************************************************************************************************************************************************************
fatal: [10.128.12.91]: FAILED! => {"changed": false, "msg": "response group_add: invalid 'group_name': may only include letters, numbers, _, -, . and $"}
```

However I'm able to go into the web UI and create groups that include spaces within their name.
```
$ ipa group-show "trust admins"
  Group name: trust admins
  Description: Trusts administrators group
  Member users: admin, juser1
```
